language: objective-c
xcode_project: SQLPlugin.xcodeproj
xcode_scheme: SQLPlugin
osx_image: xcode7.1

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

after_success:
  - bash <(curl -s https://codecov.io/bash)
